### ISSUE TITLE
Direct link to submission after cf submit

### ISSUE THREAD

**Issue by GaurangTandon** [xalanq/cf-tool#10]
It would be helpful to provide a direct link to a submission after `cf submit`. This can be especially helpful if I get non-AC verdict and wish to investigate further the particular test case.

I think we need to add one more line around the display function.

https://github.com/xalanq/cf-tool/blob/d172e3f1c0c7ac6263fc09043071c3ccb5d0b1ff/client/watch.go#L127

Something like:

	ansi.Printf(" link: %v\n", "https:codeforces.com/contest/<contest-id>/submission/<submission-id>")

**Comment by xalanq** [comment]
Good idea.

**Comment by xalanq** [comment]
I want to add a new command to do this. 
E.g.
`cf open submission [<contest-id>] <submission-id>`
what do you think?

**Comment by GaurangTandon** [comment]
Well you could shorten it to just an `[s]`, like you do for `cf pull [ac]`. Alternatively, you could enable tab completion so typing submission wouldn't be that, though I am not sure how to enable tab completion there.

Why not put the submission link in the `cf submit` output though?

**Comment by xalanq** [comment]
`cf open [s <submission-id>]` is OK.
If I put the submission link in `cf submit`, it cannot open that link by `click` or `ctrl + click` (hard to wrap URL into hyper link in windows terminal)

**Comment by xalanq** [comment]
`cf sid <submission-id> [<contest-id>]`

**Comment by infixint943** [comment]
Can this be integrated along with `cf submit` command?

**Comment by xalanq** [comment]
> Can this be integrated along with `cf submit` command?

Nice idea. I think it can be saved in `~/.cfsession`. I'll handle it

**Comment by xalanq** [comment]
Done. Now just use `cf sid` to open the last submission's page~
