### ISSUE TITLE
Print more descriptive error on cf parse

### ISSUE THREAD

**Issue by GaurangTandon** [xalanq/cf-tool#11]
For some unknown reason since today I had been unable to parse any problem. After few minutes fiddling with it I finally figured out I was logged out. I do not understand why I got logged out in the first place, but even if I was, a simple error message could have helped me resolve the issue quicker.

From the code it is clear the code already knows the problem that leads to an error (the variable `err`). So, I think we only need to display that error along side the Failed message here.

https://github.com/xalanq/cf-tool/blob/1d2bc167d75a69d5fb2132f2214df4e7d1e5db40/client/parse.go#L111

Thoughts?

**Comment by xalanq** [comment]
Thanks for your feedback
