### ISSUE TITLE
How To Add cf in PATH

### ISSUE THREAD

**Issue by Yash1256** [xalanq/cf-tool#116]
I have SUCCESSFULLY completed all the installation Steps but still I am unable to use the cf command and I am not getting how to add cf command in my PATH in mac I, plz help me out.

**Comment by kushalp13** [comment]
I also couldn't figure it out. I've added the path using export though it's not working.

**Comment by Yash1256** [comment]
I have added the path in the .zshrc file as I am a mac User 
`export GOPATH=/Users/$USER/go`
`export PATH=$GOPATH/bin:$GOROOT/bin:$PATH`
`export PATH=$GOPATH/src/github.com/xalanq/cf-tool:$PATH`
These were the Paths which I added in .zshrc file 
It Worked for me

**Comment by kushalp13** [comment]
Thanks a lot. it worked.

**Comment by shettykaran21** [comment]
Thanks a lot!
