### ISSUE TITLE
Cf parse should attempt to login instead of failing directly

### ISSUE THREAD

**Issue by GaurangTandon** [xalanq/cf-tool#12]
Hi, sorry for spamming with so many requests. This isn't really urgent so feel free to take your time :)

I have noticed that if I perform `cf parse` without being logged in (and I have no idea why I always get logged out after a day or two), it just fails. See #11.

However, if I perform `cf submit`, it tries to log me back in if I am logged out.

```
Submit 1169 C GNU G++14 6.4.0
Not logged. Try to login
Login sigma_g...
Succeed!!
Submit 1169 C GNU G++14 6.4.0
```

Could similar feature be added for cf parse? I looked up the code and it seems the `loginAgain function is needed somehow.

https://github.com/xalanq/cf-tool/blob/55bbcf06ff99b66863f278a1dbbbbdf42a461757/cmd/cmd.go#L178

**Comment by xalanq** [comment]
OK. I'll fix it in 30mins

**Comment by GaurangTandon** [comment]
Great thanks! :D
