### ISSUE TITLE
How to use it in macOS with cpEditor/SublimeText?

### ISSUE THREAD

**Issue by dhimanda** [xalanq/cf-tool#129]
I have downloader **cf_v1.0.0_darwin_64.zip** for my **MacBook m1** 
But I don't understand how to use it in macOS! 
Please can anyone guide me? 
I want to use it with [EP EDITOR](https://cpeditor.org/) or SublimeText.

**Comment by dhimanda** [comment]
I solved it.

**Comment by vishal-chdhry** [comment]
@dhimanda I am facing the same issue can you please tell me how to fix it?
