### ISSUE TITLE
Submitting a solution with an ext that wasn't added will submit an unexpected file instead

### ISSUE THREAD

**Issue by wdsrocha** [xalanq/cf-tool#14]
In the following image, the `unrelated_file.py` is submitted.

![cf submit 1000 a wrong_filename random_002](https://user-images.githubusercontent.com/26108090/59165366-a3ffb200-8ae8-11e9-933e-a8925cab9b3e.png)

Is this a bug or just an undocumented behavior? Either way, in my opinion, printing a warning notifying the user about the "file swap" would be good enough.

**Comment by xalanq** [comment]
Thanks for your feedback~
