### ISSUE TITLE
Cannot find csrf

### ISSUE THREAD

**Issue by saifbashar** [xalanq/cf-tool#149]
I am trying to submit my code using cf-tool but it says Cannot find csrf , What can I do?

**Comment by woshiluo** [comment]
Same problem on archlinux.

edit: I open this pr https://github.com/xalanq/cf-tool/pull/151, maybe you can try this.

**Comment by woshiluo** [comment]
https://codeforces.com/blog/entry/80151

And it seems an old problem, cf had rolled back this updates. Now it's back.

My PR could auto add RCPC Token, but i'm not sure if owner still work on this project and this pr will be merged, so until it merged you can still use the solution in this link.

**Comment by variety-jones** [comment]
@woshiluo Thanks! Your PR worked for my site [cfstress.com](https://cfstress.com/) as well.

**Comment by MaTBeuKo** [comment]
@woshiluo Thanks, works fine for me! Maybe you could also add C++20 to the template configuration?^^

**Comment by woshiluo** [comment]
> @woshiluo Thanks, works fine for me! Maybe you could also add C++20 to the template configuration?^^

@MaTBeuKo Thanks for testing! I add cpp20 in this pr, maybe you can test one more time.

**Comment by afengcodes** [comment]
> https://codeforces.com/blog/entry/80151
> 
> And it seems an old problem, cf had rolled back this updates. Now it's back.
> 
> My PR could auto add RCPC Token, but i'm not sure if owner still work on this project and this pr will be merged, so until it merged you can still use the solution in this link.

should i try this? but i can't find the ' 8) add RCPC token '  in version 1.0.0 when i enter 'cf config'. so how should i do, thanks

**Comment by afengcodes** [comment]
> Same problem on archlinux.
> 
> edit: I open this pr #151, maybe you can try this.

thank you for your fix, but how should i use, i use the released install version, and i don't know how to compile using source code.

**Comment by woshiluo** [comment]
> > https://codeforces.com/blog/entry/80151
> > And it seems an old problem, cf had rolled back this updates. Now it's back.
> > My PR could auto add RCPC Token, but i'm not sure if owner still work on this project and this pr will be merged, so until it merged you can still use the solution in this link.
> 
> should i try this? but i can't find the ' 8) add RCPC token ' in version 1.0.0 when i enter 'cf config'. so how should i do, thanks

The blog in codeforces tells that you should use this fork https://github.com/confusedman1/cf-tool.

If you want use my fork, you can download binary in https://github.com/woshiluo/cf-tool/releases/tag/v1.0.1.

**Comment by afengcodes** [comment]
> > > https://codeforces.com/blog/entry/80151
> > > And it seems an old problem, cf had rolled back this updates. Now it's back.
> > > My PR could auto add RCPC Token, but i'm not sure if owner still work on this project and this pr will be merged, so until it merged you can still use the solution in this link.
> > 
> > 
> > should i try this? but i can't find the ' 8) add RCPC token ' in version 1.0.0 when i enter 'cf config'. so how should i do, thanks
> 
> The blog in codeforces tells that you should use this fork https://github.com/confusedman1/cf-tool.
> 
> If you want use my fork, you can download binary in https://github.com/woshiluo/cf-tool/releases/tag/v1.0.1.

thank you so much, work fine !!!

**Comment by arglog** [comment]
Hi @woshiluo 
Thanks for sharing. Could you also let us know how to compile from your fork? I used the following command but `8) add RCPC token` was still not displayed in the compiled executable.
`go install github.com/woshiluo/cf-tool@latest`

**Comment by woshiluo** [comment]
> Hi @woshiluo Thanks for sharing. Could you also let us know how to compile from your fork? I used the following command but `8) add RCPC token` was still not displayed in the compiled executable. `go install github.com/woshiluo/cf-tool@latest`

In my fork it will auto add rcpc token, you don't need to set rpcp token yourself.

If you want to set rcpc token yourself, you should use this fork https://github.com/confusedman1/cf-tool.

**Comment by arglog** [comment]
> > Hi @woshiluo Thanks for sharing. Could you also let us know how to compile from your fork? I used the following command but `8) add RCPC token` was still not displayed in the compiled executable. `go install github.com/woshiluo/cf-tool@latest`
> 
> In my fork it will auto add rcpc token, you don't need to set rpcp token yourself.
> 
> If you want to set rcpc token yourself, you should use this fork https://github.com/confusedman1/cf-tool.

I installed using `go install github.com/woshiluo/cf-tool@latest` and then ran `./cf-tool race 1670`. Unfortunately, it still showed `Cannot find csrf`. Is anything that I've missed?
I was not able to use your pre-compiled binary due to a GLIBC version error.

**Comment by woshiluo** [comment]
> > > Hi @woshiluo Thanks for sharing. Could you also let us know how to compile from your fork? I used the following command but `8) add RCPC token` was still not displayed in the compiled executable. `go install github.com/woshiluo/cf-tool@latest`
> > 
> > 
> > In my fork it will auto add rcpc token, you don't need to set rpcp token yourself.
> > If you want to set rcpc token yourself, you should use this fork https://github.com/confusedman1/cf-tool.
> 
> I installed using `go install github.com/woshiluo/cf-tool@latest` and then ran `./cf-tool race 1670`. Unfortunately, it still showed `Cannot find csrf`. Is anything that I've missed? I was not able to use your pre-compiled binary due to a GLIBC version error.

My fork does not change the lib path, so it's a little diffcult to compile, here is a static compile program which is using musl, you can try this. https://github.com/woshiluo/cf-tool/releases/download/v1.0.1/cf-musl.

If I changed the libs path it will diffcult to be merged. I'm not good at using golang, if there is anyway to fix this, please, tell me.

**Comment by arglog** [comment]
Hi @woshiluo, the musl version works for me. Thanks for sharing!

**Comment by maverick729** [comment]
> > > https://codeforces.com/blog/entry/80151
> > > And it seems an old problem, cf had rolled back this updates. Now it's back.
> > > My PR could auto add RCPC Token, but i'm not sure if owner still work on this project and this pr will be merged, so until it merged you can still use the solution in this link.
> > 
> > 
> > should i try this? but i can't find the ' 8) add RCPC token ' in version 1.0.0 when i enter 'cf config'. so how should i do, thanks
> 
> The blog in codeforces tells that you should use this fork https://github.com/confusedman1/cf-tool.
> 
> If you want use my fork, you can download binary in https://github.com/woshiluo/cf-tool/releases/tag/v1.0.1.

Could you try releasing a Darwin executable as well for MacOS. I tried running the UNIX Executable but couldn't get it to work

**Comment by woshiluo** [comment]
> Could you try releasing a Darwin executable as well for MacOS. I tried running the UNIX Executable but couldn't get it to work

I added one and you can try it. I'm not sure if it works because i don't have any macos device.

**Comment by Flecart** [comment]
Why isn't this PR still merged?
