### ISSUE TITLE
cf tool logs out daily

### ISSUE THREAD

**Issue by infixint943** [xalanq/cf-tool#16]
Every day, the cf tool logs out and I have to login again. Any fix for this?
This didn't occur in the previous revisions(I think 5 revisions back)

**Comment by xalanq** [comment]
If you have been configured the username and password by `cf config login`. It should auto re-login when cf logs out.
The latest version still works for me. Even I have not used it for many days.

**Comment by xalanq** [comment]
Can you provide more details for it?

**Comment by infixint943** [comment]
After every 24 hours, the tool gets logged out, and so, when I submit a code(for the first time in the 24 hr period), it first logs in and then submits the code. What I want is that the tool shouldnt log out even after 24 hours.

**Comment by xalanq** [comment]
OK, I get it. I will try to find a way to implement the function "Remember me for a month" like Codeforces.
