### ISSUE TITLE
Default option for pull

### ISSUE THREAD

**Issue by infixint943** [xalanq/cf-tool#17]
Can a default option be added to pull only AC solutions from a given contest?

**Comment by xalanq** [comment]
`cf pull [ac] [<contest-id>] [<problem-id>]`
so you just need to use
`cf pull ac <contest-id>`

**Comment by xalanq** [comment]
`cf pull [ac] [<contest-id>] [<problem-id>]`
so you just need to use
`cf pull ac <contest-id>`

**Comment by xalanq** [comment]
If you want to pull all contests' codes in Codeforces. You can write a simple script (bash, python, etc.) to iterate a number `i` from 1 to 2000 and execute `cf pull ac $i`

**Comment by xalanq** [comment]
I don't want to put `ac` option as default.
