### ISSUE TITLE
Bash Completion script

### ISSUE THREAD

**Issue by infixint943** [xalanq/cf-tool#18]
I know this is trivial, but can a bash completion script be made for this?

**Comment by xalanq** [comment]
BTW, here is a bash script to clone your codes of all contests.
```
for((i=1;i<=2000;i++)); do cf pull ac $i; done
```
Just use it in terminal.

**Comment by xalanq** [comment]
What I want to add in cf tool is clone **someone**'s codes not just ourselves'.

**Comment by infixint943** [comment]
What I meant by bash script was a auto-completion capability. The auto-completion that takes place while pressing the tab button. The autocompletion for the following commands:
```
  cf config (login | add | del | default)
  cf submit [<filename>]
  cf submit [(<contest-id> <problem-id>)] [<filename>]
  cf list [<contest-id>]
  cf parse [<contest-id>] [<problem-id>]
  cf gen [<alias>]
  cf test [<filename>]
  cf watch [all] [<contest-id>]
  cf open [<contest-id>] [<problem-id>]
  cf stand [<contest-id>]
  cf sid [<submission-id>] [<contest-id>]
  cf race <contest-id>
  cf pull [ac] [<contest-id>] [<problem-id>]
  cf upgrade
```

**Comment by xalanq** [comment]
I'm sorry for it...... I thought your problem is #17.
OK.....I'll try to do what you meant

**Comment by xalanq** [comment]
I found a tool https://github.com/Infinidat/infi.docopt_completion. It works for me on Ubuntu 18.04.

**Comment by infixint943** [comment]
Thanks. This works. For anyone who wants the configuration file, here it is. Copy the below file to `/etc/bash_completion.d`. Rename the below file to `cf.sh`.

[cf.txt](https://github.com/xalanq/cf-tool/files/3414582/cf.txt)
