### ISSUE TITLE
Race only works on virtual contests

### ISSUE THREAD

**Issue by infixint943** [xalanq/cf-tool#21]
What does `race` actually do? Is it intended to work on contests that are yet to be held?
In my observation, `cf race` command works well for a virtual contest. However, for a real-time contest that is going to be held, `cf race` gives a message `Cant find countdown`. I tested this on the global round yesterday, and it gave the above message...

**Comment by xalanq** [comment]
`race` command will find the countdown in Codeforces contest's page by a regular expression `class=["']countdown["'][\s\S]*?(\d+):(\d+):(\d+)`. Maybe that's wrong...
I'll try to fix it

**Comment by xalanq** [comment]
I can't reproduce the bug... Now it works for me in [Educational Codeforces Round 69 (Rated for Div. 2)](https://codeforces.com/contests/1197).

**Comment by infixint943** [comment]
Wierd. It works now! I'll try 1/2 hour before the start of the contest and respond back to you!

**Comment by infixint943** [comment]
![Screenshot from 2019-07-22 20-02-51](https://user-images.githubusercontent.com/45997896/61640878-b52d0880-acbb-11e9-8b87-4a723073b246.png)

**Comment by xalanq** [comment]
Wierd...

**Comment by xalanq** [comment]
I try to use another way to implement this.
