### ISSUE TITLE
clone 操作时可能触发 Too many requests

### ISSUE THREAD

**Issue by hydingsy** [xalanq/cf-tool#24]
例子：
`388/1207 Error in 1131|50410105: Too many requests. Waiting for 500 seconds to continue.`

**Comment by xalanq** [comment]
这是由于 Codeforces 对同一 IP 进行了访问限制，一段时间内最多能请求的次数不会太多，所以我就加了个等待 500 秒的时间，过了 500 秒会继续的，不必担心。

**Comment by xalanq** [comment]
你还可以多次使用 clone 命令来进行增量更新。

**Comment by xalanq** [comment]
解决办法可能就是弄一个 IP 池什么的。但是想想 clone 命令用的不会很频繁，所以就挂着这个命令给他跑几个小时就好了（提交个数像 tourist 那样多时大概就 2 个多小时）。
