### ISSUE TITLE
cf gen should be executed automatically

### ISSUE THREAD

**Issue by infixint943** [xalanq/cf-tool#25]
`cf gen` and `cf parse` should go hand in hand, atleast while parsing individual problems.
Running `cf parse` should also run `cf gen` in the respective directories.

**Comment by xalanq** [comment]
It's good while parsing single problem. I'll consider your thought.
It's bad while parsing a contest. Because there is a timestamp in each code.

**Comment by GaurangTandon** [comment]
@xalanq Can you please tell what you mean by "there is a timestamp in each code"?

**Comment by xalanq** [comment]
@GaurangTandon OK, that's should be "there **could be** a timestamp in each code".

Somebody may want to record the starting time of each problem, so he/she can put the timestamp in the code.

In usage:
```
Script in template:
  Template will run 3 scripts in sequence when you run "cf test":
    - before_script   (execute once)
    - script          (execute the number of samples times)
    - after_script    (execute once)
  You could set "before_script" or "after_script" to empty string, meaning not executing.
  You have to run your program in "script" with standard input/output (no need to redirect).

  You can insert some placeholders in your scripts. When execute a script,
  cf will replace all placeholders by following rules:

  $%path%$   Path to source file (Excluding $%full%$, e.g. "/home/xalanq/")
  $%full%$   Full name of source file (e.g. "a.cpp")
  $%file%$   Name of source file (Excluding suffix, e.g. "a")
  $%rand%$   Random string with 8 character (including "a-z" "0-9")
```
and a template:
```
/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (win, osx, linux)
 * Author: $%U%$
 * Time: $%Y%$-$%M%$-$%D%$ $%h%$:$%m%$:$%s%$
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;

int main() {
    ios::sync_with_stdio(false);
    cin.tie(0);
    
    return 0;
}
```

If the user run `cf gen`, then the code will contain the starting time.

**Comment by GaurangTandon** [comment]
I understand, however, not all of us insert timestamps into our code. I think if you could add an extra option to "autorun cf gen while doing cf parse", it would be very useful for several of us.

**Comment by xalanq** [comment]
> I understand, however, not all of us insert timestamps into our code. I think if you could add an extra option to "autorun cf gen while doing cf parse", it would be very useful for several of us.

Good idea!
