### ISSUE TITLE
[Feature needed] Problem solving statistics

### ISSUE THREAD

**Issue by VincentXWD** [xalanq/cf-tool#26]
I guess most of users use this tool to do exercise on codeforces. So I hope this tool has the feature.
The command "cf stats" returns statistics of user's problem solving statistics. Like solved&unsolved problems number, AC ratio, solved&unsolved problem in some tags(like string, math, etc). I think this feature can make users have a better knowledge of their problem solving status in codeforces.

**Comment by GaurangTandon** [comment]
There's already an [online utility](https://cfviz.netlify.com/) for that. Also it has nice graphs and all, so I am not sure if `cf stats` would be able to compete against that.

**Comment by xalanq** [comment]
That's so cool. So I don't need to do that. Close it.

**Comment by VincentXWD** [comment]
> There's already an [online utility](https://cfviz.netlify.com/) for that. Also it has nice graphs and all, so I am not sure if `cf stats` would be able to compete against that.

That's cool. Thanks.
