### ISSUE TITLE
watch 指令增加查看某一道题的提交记录的功能

### ISSUE THREAD

**Issue by cometeme** [xalanq/cf-tool#27]
目前使用 `watch` 指令可以查看某一场比赛的提交记录，已经非常实用了。不过在某些情况下我希望只查看某一题的历史记录，希望能够增加一下这个功能。

It's very useful to use `watch` to search my previous submissions in a single contest, but sometimes I want to check my submissions on a single problem, hope you can add this feature.

**Comment by xalanq** [comment]
OK, I'll try to fix the format `cf watch [all] [<contest-id>]` to `cf watch [all] [<contest-id>] [<problem-id>]` (Maybe it's a illegal format of docopt, but I'll try)

**Comment by xalanq** [comment]
I'm confused. If I use `cf watch [all] [<contest-id>] [<problem-id>]`, that means I must type `<contest-id>` before the `<problem-id>` although I'm inside the directory of the `<contest-id>`.

Is there any good idea?

**Comment by cometeme** [comment]
> I'm confused. If I use `cf watch [all] [<contest-id>] [<problem-id>]`, that means I must type `<contest-id>` before the `<problem-id>` although I'm inside the directory of the `<contest-id>`.
> 
> Is there any good idea?

I think we can read multiple inputs, and check them by following conditions:

- if we get two inputs, it must be <contest-id> and <problem-id>, like `1000 A`.
- if we get one inputs, there can be three situations:
    - the inputs looks like `1000`, it's all numbers, then it must be <contest-id>
    - the inputs looks like `1000A` or `1010D1`, composed of digits and letters, then you can split it into <contest-id> and <problem-id> like `1000 A` or `1010 D1`
    - the inputs is start with a letter, like `A` or `D1`, then it means a <problem-id>, so you can use the directory as <contest-id>

**Comment by xalanq** [comment]
Yeah. I agree with you. That's what I want to do. But it's unfriendly to the docopt usage document, and I need to write more explanations in README. Thoughts?

**Comment by cometeme** [comment]
Let's ignore the case2-2 write before, since it's hard to explain in docs:
> the inputs looks like 1000A or 1010D1, composed of digits and letters, then you can split it into <contest-id> and <problem-id> like 1000 A or 1010 D1

I think the doc can be write like this:

Usage:
`cf watch [all] [<contest-id>] [<problem-id>]`

Examples:
`cf watch [all] 100`: Watch the (first 10 / all) submissions of contest 100. If you are in the directory of current contest, the `<contest-id>` an be omitted.

`cf watch [all] 100 a`: Watch the (first 10 / all) submissions of problem 100A. If you are in the directory of current contest, the `<contest-id>` an be omitted.

**Comment by xalanq** [comment]
I'll use this one `cf watch [all] [<contest-id>] [<problem-id>]` in the next minor version. Because I need to fix all other issues quickly :)

In the next big update, I'll add more features.
