### ISSUE TITLE
It would be extremely useful if you make a vscode extension.

### ISSUE THREAD

**Issue by Salil03** [xalanq/cf-tool#32]
It would be extremely usefull if you make a vscode extension. Many users use vscode for cp and integrating this tool in the vscode framework would save time for a lot of them.

**Comment by xalanq** [comment]
I would like to do that too. But I don't have enough time to do that now, I'm really busy in the next semester. I hope someone could handler it.

**Comment by Salil03** [comment]
Fair enough

**Comment by GaurangTandon** [comment]
Hi, even I use VS Code for codeforces, but I use the integrated terminal mostly. 
I'm curious as to what features you would expect from a VS Code extension @Salil03 . If you elaborate, I might try to implement it.

**Comment by Salil03** [comment]
I would love to have all the features of acmx extension in vscode + being able to submit code using command line.

But I think that would be really hard to make.

**Comment by ZZYSonny** [comment]
I've added very basic cf-tool integration to vscode using tasks and keyboard shortcut, which should be enough for practicing.  In my configuration:

Crtl+2: Parse a contest to a directory, which will ask you for the contest ID
Crtl+3: Test current file (must be generated from a parse process)
Crtl+4: Submit current file (must be generated from a parse process)

To use it, you can merge my configuration into your tasks.json and keyboard.json. Do not forget to change the directory (cwd) in CF-Parse. 
[tasks.txt](https://github.com/xalanq/cf-tool/files/3508212/tasks.txt)
[keybindings.txt](https://github.com/xalanq/cf-tool/files/3508213/keybindings.txt)

**Comment by ZZYSonny** [comment]
Now I've added most features using menus in vscode.
To call the menu, use crtl+1

Configurations:
[tasks.txt](https://github.com/xalanq/cf-tool/files/3508614/tasks.txt)
[keybindings.txt](https://github.com/xalanq/cf-tool/files/3508615/keybindings.txt)

Screenshots:
![image](https://user-images.githubusercontent.com/28442838/63152739-22278a00-c03f-11e9-99c0-4dae0ccedabb.png)
![image](https://user-images.githubusercontent.com/28442838/63152756-2bb0f200-c03f-11e9-9242-46a89fa0a6d7.png)

**Comment by Salil03** [comment]
Really excellent Keep up the good work

**Comment by Salil03** [comment]
You can use [competitive-companion](https://github.com/jmerle/competitive-companion) to parse from websites other than codeforces

**Comment by xalanq** [comment]
Close it.
