### ISSUE TITLE
Is there any way to just open the complete problems set but not all the problems when "cf race xxx" is processed?

### ISSUE THREAD

**Issue by CoderOJ** [xalanq/cf-tool#35]
Is there any way to just open the complete problems set but not all the problems when "cf race xxx" is processed?(I know nothing about go)

**Comment by xalanq** [comment]
Do you mean the problem list?
But I think I will accept the idea from #34

**Comment by xalanq** [comment]
Open both `dashboard` and `problems` when `cf race xxx`
