### ISSUE TITLE
The error with command "del" in windows.

### ISSUE THREAD

**Issue by hydingsy** [xalanq/cf-tool#36]
![image](https://user-images.githubusercontent.com/43287062/64470918-30b81b80-d17d-11e9-833e-f88c47843d7c.png)

Here is my configuration: `"after_script": "del $%file%$.exe"`

**Comment by xalanq** [comment]
Got it. I have reproduced that.

**Comment by xalanq** [comment]
Use this
`cmd.exe /C del $%file%$.exe`
I'll notice this in `cf config`

**Comment by xalanq** [comment]
https://stackoverflow.com/questions/44833044/executable-files-not-in-path-go
