### ISSUE TITLE
Navigate to created directory on parse

### ISSUE THREAD

**Issue by infixint943** [xalanq/cf-tool#37]
Navigating to the problem code folder on parsing individual problems, and to the contest folder on contest parse would be very helpful. Almost always I execute `cd <contest code>/<problem code>/` when parsing individual problems, and `cd <contest code>/`while parsing an entire contest.

**Comment by xalanq** [comment]
You can parse an individual problems by using `cf parse <contest-id> <problem-id>`, then the samples will be fetched at `./<contest-id>/<problem-id>` (It will not fetch other problems).
Or you can make the directory by yourself, then `cd <contest-id>/<problem-id>/`. Now you just need to use `cf parse` without any argument to fetch all samples into current directory

**Comment by infixint943** [comment]
That is not what I meant! What I wanted to say was this:
![image](https://user-images.githubusercontent.com/45997896/64668525-83465000-d47b-11e9-99fd-bfdcf63a1a05.png)
Notice that I navigate to the directory (`cd 1000/a/`) where the parsed problem is stored. If the tool would automatically navigate to the created directory, it would be helpful.
In this case, after parsing the problem it should automatically navigate to the directory `1000/a/`. If I parsed the entire contest, it should navigate to `1000/`.

**Comment by xalanq** [comment]
I'm sorry for my wrong understanding..
As I know, there is no way to do that in an individual program. Changing something of system terminal is not safe so the system does not allow the other process to change the terminal state. (But you can use bash script to do that)
See: <https://stackoverflow.com/questions/52435908/how-to-change-the-shells-current-working-directory-in-go>

**Comment by infixint943** [comment]
Fair enough!

**Comment by xalanq** [comment]
But you can use a script to do that.
Save it to `parse-contest`

```bash
#!/bin/bash
cf parse $1
cd $1
```

Then `chmod +x parse-contest && sudo mv parse-contest /usr/local/bin`. Now you can use `parse-contest 1111` to parse a contest and enter the sub-directory.

Same as `parse-problem`

```bash
cf parse $1 $2
cd $1/$2
```
