### ISSUE TITLE
No Countdown Found

### ISSUE THREAD

**Issue by dujoker70** [xalanq/cf-tool#39]
Why this shows when I run "cf race #(some contest id)"

**Comment by xalanq** [comment]
Can you provide more details?
- Check whether you have logged in or not.
- Use `cf --version` to print the version and show it to me.
- Give me the `contest-id`.

**Comment by dujoker70** [comment]
cf version = Codeforces Tool (cf) v0.3.2
contest-id was 1221

**Comment by xalanq** [comment]
Please upgrade it to the latest version. <https://github.com/xalanq/cf-tool/releases>
Thanks!
