### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by xalanq** [xalanq/cf-tool#40]
I'll try to make it as same as Codeforces.
- [x] case sensitive?
- [x] email?

<https://codeforces.com/blog/entry/66552?#comment-544259>

**Comment by pratapaditya1997** [comment]
Hi Alan,
Please let me take this issue as my first contribution towards the project.
I have almost completed the coding part, just adding some null checks and will do some testing.
I will submit the PR in 1-2 days

**Comment by xalanq** [comment]
close it. See #43
