### ISSUE TITLE
Bash aliases in the before_script and after_script

### ISSUE THREAD

**Issue by GaurangTandon** [xalanq/cf-tool#45]
I have defined a custom bash alias `gww` that is basically a wrapper for `g++` with lots of warning flags added.

I wish to use `gww` in the `before_script` parameter of my `.cfconfig` template.

However, it fails with:

```
gww f.cpp -o f -g
exec: "gww": executable file not found in $PATH
```

I even tried

```
source ~/.bash_aliases && gww f.cpp -o f -g
exec: "source": executable file not found in $PATH
```

Could you suggest any alternatives? (apart from having to create a `gww` executable andn adding it to path)

**Comment by user202729** [comment]
`bash -c 'gww ...'`?

This issue is not a bug in the program. You should probably ask on Codeforces instead.
