### ISSUE TITLE
Wrong error message for PDF based problem statements

### ISSUE THREAD

**Issue by GaurangTandon** [xalanq/cf-tool#46]
The message on trying `cf parse 180 a` is very confusing:

```
Failed 180 a
Not logged. Try to login
Login sigma_g...
Succeed!!
Failed 180 a
Not logged in
```

Note that [180A](https://codeforces.com/contest/180) is not available as a webpage but as a PDF, perhaps that is what contributes to the error.

So, could the error message be fixed?

**Comment by user202729** [comment]
I don't know what's your problem, but:

* 180A is available as a web page.
* When I parse a problem with only PDF statement this happens:

```
$ cf parse 101156 A
Failed 101156 a
Cannot parse sample with input 0 and output 0
```

**Comment by GaurangTandon** [comment]
> 180A is available as a web page

Indeed, that's surprising. I'm pretty sure it was a pdf, but nevertheless.

> I don't know what's your problem

The error message could be edited to reflect the actual problem: that the parsing fails due to it being a pdf. That is not very evident from the current error message.

**Comment by xalanq** [comment]
Close it.
