### ISSUE TITLE
Bug in command[Pull]

### ISSUE THREAD

**Issue by 4thcalabash** [xalanq/cf-tool#5]
When I use command [pull] to pull my code from contest 1156 problem b.

The code I got is the code in the problem statement instead of the code I submitted.

**Comment by xalanq** [comment]
Can you provide more details? e.g. screenshots.

**Comment by xalanq** [comment]
It works for me.

![QQ截图20190502164320](https://user-images.githubusercontent.com/30496124/57064630-7198b300-6cf9-11e9-913d-2a7e042a187f.png)

**Comment by xalanq** [comment]
If the problem statement was appeared. The code should be fetched into your sub directory. Please check again.

**Comment by 4thcalabash** [comment]
This bug doesn't appear when use `cf pull 1156 b`.
When I use `cf pull 1156`, I got wrong code of problem b.

**Comment by 4thcalabash** [comment]
![TIM图片20190502164402](https://user-images.githubusercontent.com/26065089/57064740-cf2cff80-6cf9-11e9-9e53-ce6a4dd0bd1a.png)
![TIM图片20190502164121](https://user-images.githubusercontent.com/26065089/57064749-d9e79480-6cf9-11e9-9e28-1e498ddc33ed.png)

**Comment by xalanq** [comment]
Let me check your submission~

**Comment by 4thcalabash** [comment]
here is my [code](http://codeforces.com/contest/1156/submission/53622508) of problem b.

And when I use `cf pull 1156 b`,I get my code.
![TIM图片20190502165022](https://user-images.githubusercontent.com/26065089/57064984-93466a00-6cfa-11e9-8dae-d5fa6fddb7ec.png)

**Comment by 4thcalabash** [comment]
I just used the pac mode of the ssr proxy, and the code that was pulled down in this mode is wrong.
When I close the proxy, the pull code is correct.

**Comment by xalanq** [comment]
It's weird. It seems like codeforces redirect the URL to homepage.
`cf pull 1156 b` and `cf pull 1156` use the same function to work. I have no idea why the first command worked but the other failed.
Did the other codes have the same problem?

**Comment by 4thcalabash** [comment]
As far as I know, only 1156 b has this problem.
Maybe it is related to SSR's PAC mode.

**Comment by xalanq** [comment]
I will try to simulate the environment you had at night: Use socks5 proxy and copy your code to submit.

**Comment by xalanq** [comment]
Emmmmmmm
Tried..But it still worked for me.
QAQ

**Comment by 4thcalabash** [comment]
Maybe SSR should be responsible for this. 233
