### ISSUE TITLE
submit not working

### ISSUE THREAD

**Issue by ahidalgob** [xalanq/cf-tool#50]
Everything was working all right today and suddenly I started getting this:

```
Submit 1186 A Haskell GHC 8.6.3
Not logged. Try to login
Login lmno...
Succeed!!
Submit 1186 A Haskell GHC 8.6.3
Not logged in
```
And it exits

I was already logged in, and even if I log in again (which goes fine), I get the same when submitting.

Codeforces Tool (cf) v0.8.2

Thank you!

**Comment by alexanderzx360** [comment]
Came here to report this, exactly the same thing happening to me on v0.8.2 and even switch users to see if it was a problem with my account, but submit is not working (parse works just fine).

Thanks.

**Comment by ericbrandwein** [comment]
I think the issue is with codeforces, the URL that cf-tool is trying to reach is down: https://codeforces.com/contest/478/submit.


![screenshot](https://user-images.githubusercontent.com/11294856/69104018-c3125080-0a45-11ea-9f2f-43b7c1ad0820.jpg)

**Comment by ahidalgob** [comment]
Submission seems to be working all right again, so yes, it was a codeforces issue. Thanks!

Note this: I've been getting that "Oops! Probably Codeforces can't be reached right now or your internet connection is broken" message lately in random Codeforces URLs, even the main page, but reloading once or twice usually fixes it, maybe that can help to overcome this issue... hopefully, we'll stop getting that message from codeforces and that would be it :)
