### ISSUE TITLE
Warn of non standard IO while running cf test

### ISSUE THREAD

**Issue by GaurangTandon** [xalanq/cf-tool#52]
Consider this question: https://codeforces.com/problemset/problem/35/D It uses non-standard IO.

Far too many times I find myself running `cf submit` immediately after `cf test` passes. It would be useful if `cf test` would warn me that the problem requires non-standard IO, so that I would add the corresponding `freopen` statements to my C++ source code before submitting the code instead of getting a RE on test 1.

**Comment by user202729** [comment]
I think it makes more sense to warn in the `cf parse`, because `cf test` doesn't have access to the problem statement.

**Comment by Nojus297** [comment]
That warns you when parsing.
And when you are finally submitting this warning would be forgotten miles away.

**Comment by xalanq** [comment]
I'll add some warns when parsing

**Comment by user202729** [comment]
There are problems with italic input/output specifier such as https://codeforces.com/gym/102354/problem/B , but is still standard input/output.

**Comment by xalanq** [comment]
> There are problems with italic input/output specifier such as https://codeforces.com/gym/102354/problem/B , but is still standard input/output.

lmao  haaaaaaaaha
