### ISSUE TITLE
Can the password be moved to a separate file?

### ISSUE THREAD

**Issue by user202729** [xalanq/cf-tool#53]
I'm thinking about using git to store my configuration files online, however from my reading of the source code, given a `.cfconfig` file it's possible to get the plain text password.

Is it possible to move the password to a separate file (for example `.cfcredential`)? For reference, git supports storing password indefinitely, but the password is stored (in plain text) in the `~/.git-credentials` file.

**Comment by xalanq** [comment]
Good idea~

**Comment by xalanq** [comment]
I'll store them in `~/.cfsession`

**Comment by xalanq** [comment]
Because I think the cookie is an important credential too

**Comment by user202729** [comment]
Note that changing the config file path means:

* The password will still be stored in the old .cfconfig file (user would need to manually delete it.
* The user would need to reconfigure the templates(they could simply copy it from the old config file, but only if they know about it.)

**Comment by xalanq** [comment]
> Note that changing the config file path means:
> 
> * The password will still be stored in the old .cfconfig file (user would need to manually delete it.
> * The user would need to reconfigure the templates(they could simply copy it from the old config file, but only if they know about it.)

If the user re-login, the configuration file will be updated.

**Comment by xalanq** [comment]
BTW, in the latest version (>0.9.0, like master branch), the configuration file will be updated when user use `cf`, whatever what he/she used.

**Comment by user202729** [comment]
> If the user re-login, the configuration file will be updated.

What about the templates?...

**Comment by xalanq** [comment]
> > If the user re-login, the configuration file will be updated.
> 
> What about the templates?...

Sorry, I just checked the code (v0.9.0). It had the feature above.
I meant if the user just move `~/.cfconfig` to `~/.cf/config`, in the next run of the `cf`, the redundant information will be deleted. So the username and password will be deleted and the other things will be kept.

**Comment by user202729** [comment]
Okay. But users who don't know about that file will not be able to do that. The program should inform the user, or automatically move the file if the source is present and not the target..

**Comment by xalanq** [comment]
Well, the upgrade command does not support too many functions. I have updated the release notes. Thanks a lot!

**Comment by xalanq** [comment]
That's why I added an `Attention` in the release note. I have no way to do that better. Sorry~
