### ISSUE TITLE
Set proxy in the config

### ISSUE THREAD

**Issue by ouuan** [xalanq/cf-tool#55]
Although it's able to use global proxy, it's better to be able to set proxy for cf-tool.

**Comment by xalanq** [comment]
Running on it

**Comment by ouuan** [comment]
![image](https://user-images.githubusercontent.com/30581822/75427473-82e63680-5981-11ea-85d2-5473a767190e.png)

I can't see this config.

**Comment by xalanq** [comment]
> ![image](https://user-images.githubusercontent.com/30581822/75427473-82e63680-5981-11ea-85d2-5473a767190e.png)
> 
> I can't see this config.

Please wait for the next release version~
I'm still fixing other issues.

**Comment by ouuan** [comment]
I compiled from the HEAD of master.

**Comment by xalanq** [comment]
The HEAD of master has already contained this feature. Please try again?

**Comment by ouuan** [comment]
> The HEAD of master has already contained this feature. Please try again?

I've tried many times.

**Comment by xalanq** [comment]
> > The HEAD of master has already contained this feature. Please try again?
> 
> I've tried many times.

Maybe you forgot to copy the file to your PATH

**Comment by ouuan** [comment]
Can you see that "Codeforces Tool (cf) v0.8.3"?

**Comment by xalanq** [comment]
![image](https://user-images.githubusercontent.com/30496124/75427860-37805800-5982-11ea-8575-40d1624dfb6d.png)

**Comment by ouuan** [comment]
Sorry, I was using e3546a6.

![image](https://user-images.githubusercontent.com/30581822/75428024-7c0bf380-5982-11ea-95e7-ffb26c254b5b.png)

But still the same.

**Comment by ouuan** [comment]
BTW: `go version go1.13.7 linux/amd64`

**Comment by xalanq** [comment]
It seems like an impossible problem. I don't know why XD.
You can open the file `./cmd/config.go` and see the code of "proxy"

**Comment by ouuan** [comment]
![image](https://user-images.githubusercontent.com/30581822/75428452-28e67080-5983-11ea-8faa-ce3e396e89ad.png)

![image](https://user-images.githubusercontent.com/30581822/75428590-66e39480-5983-11ea-843b-ad6ffe15ab96.png)

**Comment by xalanq** [comment]
See line 20 :D
So I think there were something weird on your computer

**Comment by ouuan** [comment]
Solve.

It's about cache,  `rm -rf ~/go` and download the modules again helps.

**Comment by xalanq** [comment]
haha. I met this cache bug too. But I solved it by `go clean`.

**Comment by xalanq** [comment]
The latest version is unstable. I'm changing a lot of things.

**Comment by xalanq** [comment]
Maybe I could release a new version tonight.

**Comment by ouuan** [comment]
> haha. I met this cache bug too. But I solved it by `go clean`.

I tried `go clean`, `go clean --cache`, `go clean -cache -modcache -i -r` but none of them worked.
