### ISSUE TITLE
panic: interface conversion: interface {} is nil, not float64

### ISSUE THREAD

**Issue by UncleGrandpa925** [xalanq/cf-tool#56]
I run `cf clone ac UncleGrandpa`

It ran until `139/3299` then crashed:
Here is the log:
```
panic: interface conversion: interface {} is nil, not float64

goroutine 1 [running]:
github.com/xalanq/cf-tool/client.(*Client).Clone(0xc000168230, 0x7ffeefbffba4, 0xc, 0xc00001a004, 0x23, 0x1, 0x0, 0x0)
	C:/project/go-project/src/github.com/xalanq/cf-tool/client/clone.go:133 +0x16a5
github.com/xalanq/cf-tool/cmd.Clone(0xc0000836b0, 0xc0000836b0, 0x139d809)
	C:/project/go-project/src/github.com/xalanq/cf-tool/cmd/clone.go:21 +0x185
github.com/xalanq/cf-tool/cmd.Eval(0xc0000836b0, 0xc0000836b0, 0x13a106a)
	C:/project/go-project/src/github.com/xalanq/cf-tool/cmd/cmd.go:46 +0x553
main.main()
	C:/project/go-project/src/github.com/xalanq/cf-tool/cf.go:124 +0x1e9
```
Thank you for creating this wonderful tool!

**Comment by xalanq** [comment]
I'm sorry bro. I have no time to fix this bug. You can create a new issue
in GitHub https://github.com/xalanq/cf-tool/issues ad ask for a help.
Really sorry

**Comment by Nojus297** [comment]
This happens because the submission doesn't have contest id.
Quick fix would be to ignore such submissions.

**Comment by xalanq** [comment]
> This happens because the submission doesn't have contest id.
> Quick fix would be to ignore such submissions.

Thanks～I'll fix it
