### ISSUE TITLE
Support group and acmsguru

### ISSUE THREAD

**Issue by xalanq** [xalanq/cf-tool#61]
support links like `https://codeforces.com/group/iHchP1s3j1/contest/100263`

**Comment by user202729** [comment]
And acmsguru.

**Comment by xalanq** [comment]
> And acmsguru.

What's that?

**Comment by user202729** [comment]
https://codeforces.com/blog/entry/59070

**Comment by xalanq** [comment]
Almost all feature of acmsguru have been supported.
