### ISSUE TITLE
与vim的兼容性

### ISSUE THREAD

**Issue by thallium** [xalanq/cf-tool#73]
在vim里用指令，不管是直接输
`:!cf test`
还是用脚本先开一个终端再执行cf test，都会出现cannot find any sample file
昨天还好好的，我好像也没改什么东西，不好意思打扰了/捂脸

**Comment by xalanq** [comment]
请提供一下
- `$ cf --version` 版本
- `$ ls` 目录
- `$ pwd` 路径
- `$ cat ~/.cf/config` 配置信息

**Comment by thallium** [comment]
今天突然又好了……好迷

**Comment by thallium** [comment]
问题好像是如果从终端启动vim就没事，如果直接双击cpp文件启动的vim就会这样

**Comment by BBBob** [comment]
@thallium 请提供一下在双击cpp启动vim后，使用`:!pwd`输出的路径，以及你的cpp文件所在路径，可能是vim的启动路径问题。

**Comment by thallium** [comment]
我前几天发现了，确实是vim的问题，在.vimrc里加一行`set autochdir`就行了
