### ISSUE TITLE
Getting logged out from browser after doing cf submit

### ISSUE THREAD

**Issue by GaurangTandon** [xalanq/cf-tool#80]
Not sure why this is happening, but I get logged out from codeforces.com in the  browser every time I perform cf submit.

**Comment by infalmo** [comment]
Can't replicate. I face no issues.
You might want to look at [this](https://codeforces.com/blog/entry/74702) tho

**Comment by GaurangTandon** [comment]
Might be a problem during contests only. I cannot repro it now either :/ Will reopen if trouble reappears, thanks @infixint943
