### ISSUE TITLE
Asks to give the compiler version everytime before running

### ISSUE THREAD

**Issue by Raghwendra-Dey** [xalanq/cf-tool#86]
![Screenshot from 2020-04-14 19-13-07](https://user-images.githubusercontent.com/45457947/79231584-eec62500-7e83-11ea-96c6-18b9823a3551.png)
Hey,
Firstly i would like to thank you all guys for making this awesome tool, it helps me a lot!!

I created templates and chose the language as `C++17` and also gave the prescript as `g++ #%file%# -std=c++17` but still it asks me to enter the compiler version before compiling everytime (see screenshot above). Since i gave the prescript and it have all the information about the compiler version then why does this asks me about these things? Also theres this strange behaviour that in this question if i enter 0 as the index then it compiles with `c++11` instead of `c++17` which you can see in the below attached screenshot
![Screenshot from 2020-04-14 19-20-21](https://user-images.githubusercontent.com/45457947/79232215-d7d40280-7e84-11ea-9e16-3e806bbe4dbc.png)
giving any other index(other than 0) compiles with `c++17`(as expected).
I request, to please look into this issue. And if this compiler version thing is necessary then is there a way to set some default to this. Maybe if you could add this multiple language exists question while creating the template itself and set that compiler version to default in that template.

**Comment by infalmo** [comment]
Goto file ~/.cf/config
Check all templates you have configured in that. Delete the unwanted ones (delete the whole JSON data). It seems like you have duplicates in your templates configuration

**Comment by Raghwendra-Dey** [comment]
@infixint943 Thanks for the reply! I checked the said file.
The only duplicates are the `suffix` field in each template json block, I didn't clearly get the meaning of the `suffix` field, so while creating each template i left it blank. Yes, this problem might be due to this duplicate, since pre-script of first template is `c++11` and rest are `c++17`, and hence the above mentioned strange behaviour. It would be great if you could explain the use of suffix field even after mentioning the language as `c++17` and pre-script as `g++ $%full%$ -std=c++17` while creating the templates? And to which thing i should change this `suffix` to since i use multiple types of template for `c++`. Infact, all the template blocks are for `c++` only. And if `cf test` detects the compiler by the extention of the file then is there a way to set default for a particular type of file extention like `cpp`.
I am attaching the screenshot of the file here for you to have a look:

![Screenshot from 2020-04-15 18-20-46](https://user-images.githubusercontent.com/45457947/79338905-ab33ef80-7f45-11ea-856a-54bba4f4405f.png)
![Screenshot from 2020-04-15 18-14-13](https://user-images.githubusercontent.com/45457947/79338504-0c0ef800-7f45-11ea-81e1-ed7a5d2f7562.png)

**Comment by infalmo** [comment]
Here's an brief explanation about each data field :
- alias : It's the name you give the template to recognise it by. For example `CHT template` or `All macros` template.
- lang : It refers to the code of the language on cf. `GNU C++17` has id `54`.
- path : This refers to the location of the template code. When a template is generated, the corresponding file data is copied to the generated code file.
- suffix : This is to associate the template with particular files. So, if you added a suffix of `cc` to the template config, you are telling the tool to consider all files of the form `*.cc` as a valid match for the running the template on. Thus, if you add a suffix of `py`, any file of the form `*.py` will be tested / submitted based on the configurations of the corresponding code file. Usually, you'd prefer leaving it as is.
- before_script : The script to compile your code
- script : script to execute your code
- post_script : script to clean up all compiled files, etc

Coming to your problem, what has happened is, you have configured 3 templates.
The `emt.cpp`, `cp.cpp` and `chf.cpp`. So, any file with extension `*.cpp` matches all 3 of the templates. Thus, you are prompted to select the desired template configuration to run on the code file.

I suggest you to delete the templates you don't need through `cf config` and only keep the one(s) you want.

**Comment by infalmo** [comment]
> And if cf test detects the compiler by the extention of the file then is there a way to set default for a particular type of file extention like cpp

No, you can't set default compiler configurations. Actually, afaik, the only purpose the templates serve is for a quick selection of language you wish to code in. It is not for having different templates. In that case, yu may use snippets support provided by your IDE (I use VSCode, and it's pretty nice)

**Comment by Raghwendra-Dey** [comment]
> Actually, afaik, the only purpose the templates serve is for a quick selection of language you wish to code in. It is not for having different templates.

Hey thanks a lot for the nice explanation!!
I would like to suggest one thing, if the only purpose of `cf gen` is to create a file with the required extention then it would be great if `cf parse` only can do this thing, thus reducing one command and adding on speed during competition!! Or maybe there could be some flag in the`cf config` which can be configured to combine `cf gen` with `cf parse` and `cf race`.

**Comment by Raghwendra-Dey** [comment]
> > Actually, afaik, the only purpose the templates serve is for a quick selection of language you wish to code in. It is not for having different templates.
> 
> Hey thanks a lot for the nice explanation!!
> I would like to suggest one thing, if the only purpose of `cf gen` is to create a file with the required extention then it would be great if `cf parse` only can do this thing, thus reducing one command and adding on speed during competition!! Or maybe there could be some flag in the`cf config` which can be configured to combine `cf gen` with `cf parse` and `cf race`.
> 
> 

Sorry just now discovered that this thing is already implemented. Thanks a lot!
