### ISSUE TITLE
In case of runtime error print the debug statements in cf test

### ISSUE THREAD

**Issue by Raghwendra-Dey** [xalanq/cf-tool#87]
When using `cf test` for testing, in case of runtime errors the print statements doesn't get printed in the terminal. Just a error message of `runtime error` gets printed. I have tested it with normal compilation the program is printing the debug statements but when using `cf test` its not getting printed. It would be helpful to debug, using cf test itself, if it could print the debug statements as well along with the error messages. You may see in the attached screenshot, that at first when i tried to use cf test it just exited with the message of seg fault, but when i manually compiled it and ran it, it printed the debug statements("fsbja" are the words used for debugging purposes!!)

![Screenshot from 2020-04-15 01-36-42](https://user-images.githubusercontent.com/45457947/79269040-6d898500-7eb9-11ea-8a40-02334cfa77b7.png)

**Comment by infixint943** [comment]
What exactly do you want printed?
I can't determine without giving more details, regarding the test case and your code.

**Comment by infalmo** [comment]
Try printing them to stderr.

**Comment by Raghwendra-Dey** [comment]
> Try printing them to stderr.

Thanks a lot its getting printed using stderr!! Even without flushing the output.
It would be great if you could explain the reason for this behaviour.

**Comment by infalmo** [comment]
What happens is, you were previously printing to stdout. The data of stdout is compared with the expected output and the verdict (along with diff if WA) is shown. However, if there is a runtime error, the code skips the comparision of output with the answer. Thus in case of RTE, your stdout won't get printed.

Also, it's always advisable to ALWAYS use stderr while printing debug statements, as they don't interfere with your solution output and can be submitted on cf without removing the debug statements.

**Comment by infalmo** [comment]
If your issue is resolved, you may close this issue.

**Comment by Raghwendra-Dey** [comment]
> What happens is, you were previously printing to stdout. The data of stdout is compared with the expected output and the verdict (along with diff if WA) is shown. However, if there is a runtime error, the code skips the comparision of output with the answer. Thus in case of RTE, your stdout won't get printed.
> 
> Also, it's always advisable to ALWAYS use stderr while printing debug statements, as they don't interfere with your solution output and can be submitted on cf without removing the debug statements.

Thanks a lot for the explanation!!
