### ISSUE TITLE
Show memory usage of the program on `cf test`

### ISSUE THREAD

**Issue by GaurangTandon** [xalanq/cf-tool#9]
Is it possible to show memory consumption of program alongside the verdicts...

```
Passed #1 .... 0.002s/192K
Passed #2 .... 0.002s/192K
Passed #3 .... 0.002s/192K
Passed #4 .... 0.030s/10M
```

and highlight in red if it exceeds the memory limit mentioned on the problem page? I am asking because I recently overran memory by accidentally using a 5000x5000 long long int 2D vector, and got an MLE later.

**Comment by xalanq** [comment]
Show memory is OK. But check stuff is not. Because memory limit is fetched by using network, it causes lag.

**Comment by GaurangTandon** [comment]
Sorry, I do not understand how fetching memory limit causes network lag? It currently does fetch the test cases for the problem. So, fetching the memory limit value should be quite a trivial addition to that, shouldn't it?.

**Comment by xalanq** [comment]
Current version doesn't store any contest information. So to get the contest info must be fetched online. Yeah, the contest info should be stored in local, and there are many things to consider. But you need to wait some time (I'm busy)~

**Comment by xalanq** [comment]
I found getting memory usage in windows is a little bit hard :(

**Comment by GaurangTandon** [comment]
> But you need to wait some time

Sure, take your time :)

**Comment by VincentXWD** [comment]
One possible way to implement this feature is to use ulimit: https://ss64.com/bash/ulimit.html
You can set the memory limit crawled by your crawler and do the corresponding limit when running your program.
This tool can be used on Linux and OSX. As for a equivalent on Windows, check this: https://serverfault.com/questions/133122/ulimit-for-windows

**Comment by xalanq** [comment]
I'm trying https://github.com/shirou/gopsutil
It seems working.

**Comment by xalanq** [comment]
Done~ I'll release it later, because the GIF should be updated.
