### ISSUE TITLE
Java with cd gen file name

### ISSUE THREAD

**Issue by pranayagra** [xalanq/cf-tool#90]
As I am using Java for CF, is it possible that the template main class name can change as well?

**Comment by infalmo** [comment]
Could you give an example of what you wish to achieve? The question is a bit unclear

**Comment by pranayagra** [comment]
Sorry, I thought I had closed this issue. I couldn't find an option to do this in the code, so I ended up changing the code myself. But unlike C++, Java must have the same class name as the file name (If my file is named a.java, the class in the java file must be called a), but it does not seem like I can add this option to the template (hence why I changed the gen.go source code to add this option). 

While I am here, is it possible to run only one test case for some problem (for example, suppose problem "a" has 3 test cases (in1.txt, in2.txt, in3.txt). Can I pass cf test an option to specify to only run and check in2.txt?
